version: 2
updates:
- package-ecosystem: pip
  directory: "/{{cookiecutter.project_name}}"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
