@Library(['github.com/tomtom-international/jsl']) _

pythonSetupPyPipeline \
  dockerFilename: "Dockerfile.build", \
  dockerBuildArgs: "--network host", \
  pypiRepo: "{{ cookiecutter.pypi_repo }}", \
  pypiCredentials: "{{ cookiecutter.pypi_credentials_id }} ", \
  sshAgentUser: "{{ cookiecutter.ci_ssh_agent_user }}"
