@Library(value="github.com/tomtom-international/jsl@master", changelog=false) _

pythonSetupPyPipeline \
  dockerDeploy: true, \
  dockerRegistryCredentialsId: "{{ cookiecutter.docker_registry_credentials_id }}", \
  dockerRegistryUrl: "https://docker.navkit-pipeline.tt3.com", \
  pypiRepo: "{{ cookiecutter.pypi_repo }}", \
  pypiCredentialsId: "{{ cookiecutter.pypi_credentials_id }} ", \
  sshAgentUser: "{{ cookiecutter.ci_ssh_agent_user }}"
