version: 1

update_configs:
  - package_manager: "python"
    directory: "{{cookiecutter.project_name}}"
    update_schedule: "live"
    commit_message:
      prefix: "fix"
      prefix_development: "chore"
      include_scope: true
